name: technique
version:  0.2.4
synopsis: Procedures and Sequences
description: |
  A domain specific lanaguage for procedures.

stability: experimental
license: MIT
license-file: LICENSE
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2002-2019 Operational Dynamics and Others
category: Tools
tested-with: GHC == 8.6
github: oprdyn/technique

dependencies:
 - base >= 4.11 && < 5
 - ivar-simple
 - core-data >= 0.2.1
 - core-text >= 0.2.2
 - core-program >= 0.2.2
 - free
 - megaparsec
 - text
 - parser-combinators
 - prettyprinter
 - prettyprinter-ansi-terminal

ghc-options: -Wall -Wwarn -fwarn-tabs -dynamic

library:
  dependencies:
   - async
   - uuid-types
  source-dirs: lib
  exposed-modules:
   - Technique.Language
   - Technique.Quantity
   - Technique.Formatter
   - Technique.Parser
  other-modules:
   - Technique.Evaluator
   - Technique.Instantiate

executables:
  technique:
    dependencies:
     - technique
    ghc-options: -threaded -dynamic
    source-dirs: src
    main: TechniqueMain.hs
    other-modules:
     - TechniqueUser

tests:
  check:
    dependencies:
     - hspec
     - technique
    ghc-options: -threaded -dynamic
    source-dirs:
     - tests
    main: TestSuite.hs
    other-modules:
    - CheckAbstractSyntax
    - CheckSkeletonParser
    - CheckQuantityBehaviour
    - ExampleProcedure

