resolver: lts-14.11

extra-deps:
 - ivar-simple-0.3.2
 - git: http://github.com/oprdyn/unbeliever
   commit: 43688701ba367ca9d74eacb5393fa62fb060d14d
   subdirs:
    - core-text
    - core-program
    - core-data

