resolver: lts-14.16

packages:
 - /home/andrew/src/oprdyn/unbeliever/core-text
 - /home/andrew/src/oprdyn/unbeliever/core-program
 - /home/andrew/src/oprdyn/unbeliever/core-data
 - .

extra-deps:
 - ivar-simple-0.3.2

